services:
  - type: web
    name: job-portal
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    env: python
    envVars:
      - key: SECRET_KEY
        value: your-secret-value
    autoDeploy: true
