services:
  - type: web
    name: job-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    pythonVersion: 3.11
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY  
